[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "paris"
gas_price = 2000000000
gas_limit = 8000000

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]
